import type { SimulationInputs } from "@/components/InputModule";
import type { SimulationResults } from "@/lib/simulation";

interface ExportSummaryOptions {
  inputs: SimulationInputs;
  results: SimulationResults;
  scenarioName?: string;
}

const INR_PER_USD = 83;

const formatCurrency = (value: number) => {
  if (!Number.isFinite(value)) return "N/A";
  const inrValue = value * INR_PER_USD;
  if (Math.abs(inrValue) >= 10_000_000) return `₹${(inrValue / 10_000_000).toFixed(2)} Cr`;
  if (Math.abs(inrValue) >= 100_000) return `₹${(inrValue / 100_000).toFixed(1)} L`;
  return `₹${inrValue.toFixed(2)}`;
};

const formatNumber = (value: number, digits = 2) => {
  if (!Number.isFinite(value)) return "N/A";
  return value.toFixed(digits);
};

const buildSummary = ({ inputs, results, scenarioName }: ExportSummaryOptions) => {
  const title = scenarioName ?? "Current live model";
  const generatedAt = new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date());

  return `# BioGraphX Feasibility Summary

## Scenario
- Name: ${title}
- Generated: ${generatedAt}

## Key inputs
- Bagasse input: ${formatNumber(inputs.bagasseTons, 1)} tons/day
- Moisture content: ${formatNumber(inputs.moisturePercent, 1)}%
- Electricity cost: ${formatCurrency(inputs.electricityCost)}/kWh
- Labor cost: ${formatCurrency(inputs.laborCost)}/day
- Plant CAPEX: ${formatCurrency(inputs.plantCapex * 1_000_000)}
- GO market price: ${formatCurrency(inputs.grapheneMarketPrice)}/kg

## Production outputs
- Dry bagasse: ${formatNumber(results.dryBagasse, 2)} tons/day
- Biochar produced: ${formatNumber(results.biocharProduced, 2)} tons/day
- GO produced: ${formatNumber(results.goProduced, 1)} kg/day
- Monthly GO output: ${formatNumber(results.goProducedMonthly, 0)} kg/month
- Annual GO output: ${formatNumber(results.goProducedYearly, 0)} kg/year
- Carbon saved: ${formatNumber(results.carbonSaved, 0)} tCO2/year

## Financial overview
- Annual revenue: ${formatCurrency(results.yearlyRevenue)}
- Annual OPEX: ${formatCurrency(results.yearlyOpex)}
- Annual net profit: ${formatCurrency(results.yearlyProfit)}
- ROI: ${formatNumber(results.roiPercent, 1)}%
- Payback period: ${Number.isFinite(results.paybackYears) ? `${formatNumber(results.paybackYears, 1)} years` : "N/A"}
- Daily energy cost: ${formatCurrency(results.energyCostDaily)}

## Recommendation
${results.recommendation}

## Suggested next steps
${results.suggestions.map((item, index) => `${index + 1}. ${item}`).join("\n")}

---
Generated by BioGraphX.
`;
};

export const exportSimulationSummary = (options: ExportSummaryOptions) => {
  const summaryContent = buildSummary(options);
  const blob = new Blob([summaryContent], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  const safeName = (options.scenarioName ?? "current-scenario")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

  link.href = url;
  link.download = `biographx-summary-${safeName || "scenario"}.md`;
  link.click();
  URL.revokeObjectURL(url);
};
